# Generated by Django 4.2.16 on 2024-11-28 12:48

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('difficulty', models.CharField(max_length=200)),
                ('map_route', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('distance', models.FloatField()),
                ('elevation_max', models.IntegerField()),
                ('elevation_gain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.DurationField(null=True)),
                ('tokens_earned', models.IntegerField()),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('pace', models.FloatField(help_text='Minutes per kilometer', null=True)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_records', to='run_wild.questpost')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
