# Generated by Django 4.2.16 on 2024-11-25 10:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('difficulty', models.CharField(max_length=200)),
                ('map_route', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('distance', models.FloatField()),
                ('elevation_max', models.IntegerField()),
                ('elevation_gain', models.IntegerField()),
            ],
        ),
    ]
