# Generated by Django 4.2.16 on 2024-11-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_wild', '0001_initial'),
    ]

    operations = [
           migrations.RunSQL(
            sql="""
            ALTER TABLE run_wild_questrecord 
            ALTER COLUMN completion_time TYPE interval 
            USING '0'::interval;
            """,
            reverse_sql="""
            ALTER TABLE run_wild_questrecord 
            ALTER COLUMN completion_time TYPE double precision 
            USING extract(epoch from completion_time);
            """
        ),
    ]
