# Generated by Django 4.2.16 on 2024-11-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('run_wild', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.FloatField()),
                ('tokens_earned', models.IntegerField()),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run_wild.questpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
