# Generated by Django 4.2.16 on 2024-11-26 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('run_wild', '0004_questrecord_approved_alter_questrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
