# Generated by Django 4.2.16 on 2024-11-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_wild', '0005_alter_questrecord_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questrecord',
            old_name='user',
            new_name='runner',
        ),
    ]
